// <auto-generated />
using System;
using GvGRank_Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GvGRank_Server.Migrations
{
    [DbContext(typeof(VoteDbContext))]
    partial class VoteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GvGRank_Server.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<int>("Losses");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("Role");

                    b.Property<int>("Shitlo");

                    b.Property<int>("Wins");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Losses = 0,
                            Name = "Alan",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Losses = 0,
                            Name = "Andi",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Losses = 0,
                            Name = "Battle Clog",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Losses = 0,
                            Name = "Bounty",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Losses = 0,
                            Name = "Butters",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            Losses = 0,
                            Name = "Chrona",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            Losses = 0,
                            Name = "Dervish Xen",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            Losses = 0,
                            Name = "Dome",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            Losses = 0,
                            Name = "Ego",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            Losses = 0,
                            Name = "Endo",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            Losses = 0,
                            Name = "Exile",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            Losses = 0,
                            Name = "Fedex",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 13,
                            Active = true,
                            Losses = 0,
                            Name = "Gatos",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 14,
                            Active = true,
                            Losses = 0,
                            Name = "Gurerro Sauron",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 15,
                            Active = true,
                            Losses = 0,
                            Name = "Hash",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 16,
                            Active = true,
                            Losses = 0,
                            Name = "Hemo",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 17,
                            Active = true,
                            Losses = 0,
                            Name = "Ice",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 18,
                            Active = true,
                            Losses = 0,
                            Name = "Izzo",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 19,
                            Active = true,
                            Losses = 0,
                            Name = "Jake",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 20,
                            Active = true,
                            Losses = 0,
                            Name = "Kai",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 21,
                            Active = true,
                            Losses = 0,
                            Name = "Matze",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 22,
                            Active = true,
                            Losses = 0,
                            Name = "Messy",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 23,
                            Active = true,
                            Losses = 0,
                            Name = "Monky",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 24,
                            Active = true,
                            Losses = 0,
                            Name = "Nihal",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 25,
                            Active = true,
                            Losses = 0,
                            Name = "No Chance",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 26,
                            Active = true,
                            Losses = 0,
                            Name = "Pally",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 27,
                            Active = true,
                            Losses = 0,
                            Name = "Paul Yang",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 28,
                            Active = true,
                            Losses = 0,
                            Name = "Portu",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 29,
                            Active = true,
                            Losses = 0,
                            Name = "Roken",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 30,
                            Active = true,
                            Losses = 0,
                            Name = "Skittles",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 31,
                            Active = true,
                            Losses = 0,
                            Name = "Slam",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 32,
                            Active = true,
                            Losses = 0,
                            Name = "Sync",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 33,
                            Active = true,
                            Losses = 0,
                            Name = "Takida",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 34,
                            Active = true,
                            Losses = 0,
                            Name = "Teddy",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 35,
                            Active = true,
                            Losses = 0,
                            Name = "Zurrie",
                            Role = 1,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 36,
                            Active = true,
                            Losses = 0,
                            Name = "ANT Philip",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 37,
                            Active = true,
                            Losses = 0,
                            Name = "Arclite",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 38,
                            Active = true,
                            Losses = 0,
                            Name = "Aspect",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 39,
                            Active = true,
                            Losses = 0,
                            Name = "Beware",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 40,
                            Active = true,
                            Losses = 0,
                            Name = "Brent",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 41,
                            Active = true,
                            Losses = 0,
                            Name = "Candyboy",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 42,
                            Active = true,
                            Losses = 0,
                            Name = "Chijo",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 43,
                            Active = true,
                            Losses = 0,
                            Name = "Chrizzo",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 44,
                            Active = true,
                            Losses = 0,
                            Name = "Crimy",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 45,
                            Active = true,
                            Losses = 0,
                            Name = "Domi/Far Cry",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 46,
                            Active = true,
                            Losses = 0,
                            Name = "Dopos",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 47,
                            Active = true,
                            Losses = 0,
                            Name = "Enso",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 48,
                            Active = true,
                            Losses = 0,
                            Name = "Ep Loves My Babies",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 49,
                            Active = true,
                            Losses = 0,
                            Name = "Epica",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 50,
                            Active = true,
                            Losses = 0,
                            Name = "Fluxy",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 51,
                            Active = true,
                            Losses = 0,
                            Name = "Francis The Earth",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 52,
                            Active = true,
                            Losses = 0,
                            Name = "Giggler",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 53,
                            Active = true,
                            Losses = 0,
                            Name = "Godly/VERYNICE",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 54,
                            Active = true,
                            Losses = 0,
                            Name = "Hadshi",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 55,
                            Active = true,
                            Losses = 0,
                            Name = "Honk",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 56,
                            Active = true,
                            Losses = 0,
                            Name = "Honors",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 57,
                            Active = true,
                            Losses = 0,
                            Name = "Jorn",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 58,
                            Active = true,
                            Losses = 0,
                            Name = "Kam",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 59,
                            Active = true,
                            Losses = 0,
                            Name = "KO",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 60,
                            Active = true,
                            Losses = 0,
                            Name = "Kobe",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 61,
                            Active = true,
                            Losses = 0,
                            Name = "Lisek",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 62,
                            Active = true,
                            Losses = 0,
                            Name = "Lua Kavanuh",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 63,
                            Active = true,
                            Losses = 0,
                            Name = "Luv",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 64,
                            Active = true,
                            Losses = 0,
                            Name = "Maga",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 65,
                            Active = true,
                            Losses = 0,
                            Name = "Mario",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 66,
                            Active = true,
                            Losses = 0,
                            Name = "Maverick",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 67,
                            Active = true,
                            Losses = 0,
                            Name = "Miru",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 68,
                            Active = true,
                            Losses = 0,
                            Name = "Motoko",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 69,
                            Active = true,
                            Losses = 0,
                            Name = "Nick",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 70,
                            Active = true,
                            Losses = 0,
                            Name = "Ra",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 71,
                            Active = true,
                            Losses = 0,
                            Name = "Raffy",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 72,
                            Active = true,
                            Losses = 0,
                            Name = "Resi",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 73,
                            Active = true,
                            Losses = 0,
                            Name = "Rudi",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 74,
                            Active = true,
                            Losses = 0,
                            Name = "Saints",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 75,
                            Active = true,
                            Losses = 0,
                            Name = "Shisha",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 76,
                            Active = true,
                            Losses = 0,
                            Name = "Spartan (USA)",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 77,
                            Active = true,
                            Losses = 0,
                            Name = "Sven",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 78,
                            Active = true,
                            Losses = 0,
                            Name = "Tequila",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 79,
                            Active = true,
                            Losses = 0,
                            Name = "TJ",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 80,
                            Active = true,
                            Losses = 0,
                            Name = "Trunkz",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 81,
                            Active = true,
                            Losses = 0,
                            Name = "Vesto",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 82,
                            Active = true,
                            Losses = 0,
                            Name = "Yamamoto",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 83,
                            Active = true,
                            Losses = 0,
                            Name = "Yoko",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 84,
                            Active = true,
                            Losses = 0,
                            Name = "Zynkh",
                            Role = 2,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 85,
                            Active = true,
                            Losses = 0,
                            Name = "Accolade",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 86,
                            Active = true,
                            Losses = 0,
                            Name = "Akemi",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 87,
                            Active = true,
                            Losses = 0,
                            Name = "Ali",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 88,
                            Active = true,
                            Losses = 0,
                            Name = "Amnell",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 89,
                            Active = true,
                            Losses = 0,
                            Name = "Azin",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 90,
                            Active = true,
                            Losses = 0,
                            Name = "Blastoise",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 91,
                            Active = true,
                            Losses = 0,
                            Name = "Boring",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 92,
                            Active = true,
                            Losses = 0,
                            Name = "Chamalee",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 93,
                            Active = true,
                            Losses = 0,
                            Name = "Chunin",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 94,
                            Active = true,
                            Losses = 0,
                            Name = "Daenerys Del Dragon",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 95,
                            Active = true,
                            Losses = 0,
                            Name = "Demon",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 96,
                            Active = true,
                            Losses = 0,
                            Name = "DMP",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 97,
                            Active = true,
                            Losses = 0,
                            Name = "Duchesse",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 98,
                            Active = true,
                            Losses = 0,
                            Name = "Eraziel",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 99,
                            Active = true,
                            Losses = 0,
                            Name = "Fate",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 100,
                            Active = true,
                            Losses = 0,
                            Name = "Goddie",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 101,
                            Active = true,
                            Losses = 0,
                            Name = "Holye",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 102,
                            Active = true,
                            Losses = 0,
                            Name = "I Let You Live Long",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 103,
                            Active = true,
                            Losses = 0,
                            Name = "Izzy",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 104,
                            Active = true,
                            Losses = 0,
                            Name = "Jacke",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 105,
                            Active = true,
                            Losses = 0,
                            Name = "Java",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 106,
                            Active = true,
                            Losses = 0,
                            Name = "Jonas",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 107,
                            Active = true,
                            Losses = 0,
                            Name = "Karl Monky",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 108,
                            Active = true,
                            Losses = 0,
                            Name = "Kasperov",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 109,
                            Active = true,
                            Losses = 0,
                            Name = "Killing",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 110,
                            Active = true,
                            Losses = 0,
                            Name = "Lao",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 111,
                            Active = true,
                            Losses = 0,
                            Name = "Leila Of Langlar",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 112,
                            Active = true,
                            Losses = 0,
                            Name = "Luke",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 113,
                            Active = true,
                            Losses = 0,
                            Name = "Lynie",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 114,
                            Active = true,
                            Losses = 0,
                            Name = "Marley",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 115,
                            Active = true,
                            Losses = 0,
                            Name = "Math",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 116,
                            Active = true,
                            Losses = 0,
                            Name = "Moo",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 117,
                            Active = true,
                            Losses = 0,
                            Name = "Nameless",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 118,
                            Active = true,
                            Losses = 0,
                            Name = "Ne Baktin Canim",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 119,
                            Active = true,
                            Losses = 0,
                            Name = "Newty",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 120,
                            Active = true,
                            Losses = 0,
                            Name = "Noya/Martin",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 121,
                            Active = true,
                            Losses = 0,
                            Name = "Nutella/Pasco",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 122,
                            Active = true,
                            Losses = 0,
                            Name = "Oln",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 123,
                            Active = true,
                            Losses = 0,
                            Name = "Pfefferkuchen",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 124,
                            Active = true,
                            Losses = 0,
                            Name = "Puma Girly",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 125,
                            Active = true,
                            Losses = 0,
                            Name = "Purif",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 126,
                            Active = true,
                            Losses = 0,
                            Name = "Rainy",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 127,
                            Active = true,
                            Losses = 0,
                            Name = "Remede",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 128,
                            Active = true,
                            Losses = 0,
                            Name = "Robert",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 129,
                            Active = true,
                            Losses = 0,
                            Name = "Santana",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 130,
                            Active = true,
                            Losses = 0,
                            Name = "Sebbe",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 131,
                            Active = true,
                            Losses = 0,
                            Name = "Sistrens",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 132,
                            Active = true,
                            Losses = 0,
                            Name = "Smoki",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 133,
                            Active = true,
                            Losses = 0,
                            Name = "Spartan (FR)",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 134,
                            Active = true,
                            Losses = 0,
                            Name = "Stark",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 135,
                            Active = true,
                            Losses = 0,
                            Name = "Strng Jpn",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 136,
                            Active = true,
                            Losses = 0,
                            Name = "Virti",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 137,
                            Active = true,
                            Losses = 0,
                            Name = "Walky",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 138,
                            Active = true,
                            Losses = 0,
                            Name = "Willy",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 139,
                            Active = true,
                            Losses = 0,
                            Name = "Yoshi",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 140,
                            Active = true,
                            Losses = 0,
                            Name = "Zuvit",
                            Role = 3,
                            Shitlo = 0,
                            Wins = 0
                        });
                });

            modelBuilder.Entity("GvGRank_Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AntiTamper");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<int>("VoteLimit");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GvGRank_Server.Models.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int>("LoseId");

                    b.Property<int>("UserId");

                    b.Property<int>("WinId");

                    b.HasKey("Id");

                    b.ToTable("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
